#!/bin/sh /etc/rc.common

START=99
STOP=10

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

APP=relay_gateway_appd
LOGFILE=/var/log/$APP
CONFIGFILE=/etc/config/relay_gateway.cfg

start(){
        sleep 5
        service_start /usr/bin/$APP -l $LOGFILE -c $CONFIGFILE
}

stop() {
        service_stop /usr/bin/$APP
}
